[NMA-1060] Target SDK 31
dashevo/dash-wallet pull request #1027
Opened 2022-08-24 12:33 UTC by Syn-McJ

Changes necessary to target SDK 31.
Additionally, the gradle plugin is upgraded to version 7.2.2 and some related migrations were run:
<img width="263" alt="Screenshot 2022-08-22 164932" src="https://user-images.githubusercontent.com/7733989/186418916-fcd63688-3045-4e4b-aec7-efc42abcc3fe.png">

## Issue being fixed or feature implemented

## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [x] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2022-08-24 12:36 UTC, Syn-McJ commented on fastlane/Fastfile
> +    gradle(task: "test#{flavor}#{type}UnitTest")
Seems like there was an error and the flavor/type weren't actually specified for the tests, which resulted in all tests for all flavors and types being run every time.

I think my original idea was to only run flavor/type that was requested for the build itself. This should reduce the amount of time necessary to make a manual distribution build.

2022-08-24 19:08 UTC, HashEngineering requested changes
Looks good except that PR #1025, which was merged earlier today moved the `coinbase-integration` files to `coinbase` and that results in a conflict on several files.

2022-08-25 03:38 UTC, Syn-McJ commented
@HashEngineering fixed

2022-08-25 04:27 UTC, HashEngineering approved these changes

2022-08-25 04:28 UTC, merged