[ NMA-988]: Default fiat currency
dashevo/dash-wallet pull request #734
Opened 2021-08-30 14:19 UTC by ClaudeHangui

## Issue being fixed or feature implemented
Update the design of the screen which displays the list of supported fiat currencies
PS: There are no translations for the label **Select Currency**

## Checklist:

- [x] I have performed a self-review of my own code and added comments where necessary

2021-08-31 09:26 UTC, tomasz-ludek requested changes

2021-08-31 09:26 UTC, tomasz-ludek commented on wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java
> +        if (currencyCode.equalsIgnoreCase("try")) return R.drawable.turk;    //we can't use 'try' as the recource name for turkish flag as try is a reserved keyword in java. A workaround is to use re
We should avoid such weird exceptions. I would suggest to add a prefix to each resource name (e.g. "currency_code_try", or something similar). Additionally, names with such prefix would be more self-descriptive.

2021-08-31 11:20 UTC, ClaudeHangui commented on wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java
> +        if (currencyCode.equalsIgnoreCase("try")) return R.drawable.turk;    //we can't use 'try' as the recource name for turkish flag as try is a reserved keyword in java. A workaround is to use re
The implementation of this method had been updated accordingly

2021-09-08 12:34 UTC, ClaudeHangui reviewed
- Our design for the exchange rates screen takes into account the 2 entry points we have: **Settings** and **SendPayment** flows. The action to display this new UI from the **SendPayment** flow has not yet been implemented
- We removed unused variable dependencies and refactored the class as much as we could

2021-09-09 17:02 UTC, HashEngineering approved these changes
looks good and works well

2021-09-09 17:03 UTC, HashEngineering requested changes
There is a merge conflict with the Firebase Events for Settings.

2021-09-09 17:44 UTC, ClaudeHangui commented
Conflicts have been fixed

2021-09-09 18:49 UTC, merged