feat: buy dash from coinbase data-layer
dashevo/dash-wallet pull request #843
Opened 2021-12-23 12:22 UTC by ClaudeHangui

## Issue being fixed or feature implemented
This task focuses on providing data needed by the UI to perform the **buy dash from coinbase** flow:

- Get the current user's active payment methods
- Purchase order on coinbase (`buy order`)
- Completion of a purchase (`commit order`)
- Sending funds to dash wallet (`send transactions`)

## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [x] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2021-12-23 15:37 UTC, Syn-McJ reviewed
Looks fine to me, but shouldn't there be some examples of using these endpoints? I know we need UI for getting actual values the user has input, but until then some predefined mock values could be used.

2021-12-24 09:15 UTC, ClaudeHangui commented
> Looks fine to me, but shouldn't there be some examples of using these endpoints? I know we need UI for getting actual values the user has input, but until then some predefined mock values could be used.

You mean provide unit tests and set default values for the data classes ?

2021-12-29 18:27 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseBuyDashFragment.kt
> -        val paymentMethods = coinbasePaymentMethods
I moved the responsability to the VM model

2021-12-29 18:28 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseBuyDashFragment.kt
> -    private fun paymentMethodTypeFromCoinbaseType(type: String): PaymentMethodType {
responsability moved to VM

2021-12-29 18:28 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/CoinbaseServicesFragment.kt
> -        viewModel.user.observe(
user already observed in a similar fashion some lines above

2021-12-29 18:32 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/network/ResponseResource.kt
> -            ResponseResource.Loading
Launching of the progress dialog should be done on the main main thread and not on an IO thread

2022-01-17 22:28 UTC, HashEngineering commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseAuthRepository.kt
> +const val TEMP_REFRESH_TOKEN = "d28ae95beb4c5149644ee946e100479206b7204559e5944bc5ab151389a4279c"
should these be in the code, or be taken from services.properties?

2022-01-17 22:29 UTC, HashEngineering commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt
> +        */
should this still be here?

2022-01-17 22:33 UTC, HashEngineering approved these changes

2022-01-17 22:36 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt
> +        */
ahh yes, this portion is depreciated. will remove it !

2022-01-17 22:37 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/CoinBaseAuthRepository.kt
> +const val TEMP_REFRESH_TOKEN = "d28ae95beb4c5149644ee946e100479206b7204559e5944bc5ab151389a4279c"
these constants as well will be removed. They were used for testing purposes, forgot to remove it

2022-01-18 05:10 UTC, Syn-McJ requested changes
Great work, there are some minor fixes needed with AmountView and styles.

2022-01-18 05:10 UTC, Syn-McJ commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/ui/dialogs/CoinBaseErrorDialog.kt
> +            Log.e(this::class.java.simpleName, "Closing dialog")
Do we really need these error logs in the logcat? I understand if it is used for development purposes, but it should be cleaned up afterward. Having random red messages in logcat that are not actually errors is confusing.

2022-01-18 05:10 UTC, Syn-McJ commented on common/src/main/java/org/dash/wallet/common/livedata/Event.kt
> +open class Event<out T>(private val content: T) {
We have `SingleLiveEvent`, can it serve the same purpose?

2022-01-18 05:34 UTC, HashEngineering commented on .gitignore
> +wallet/schemas/*/*.json
This may have been from another PR that was merged into this PR.

2022-01-18 05:35 UTC, HashEngineering commented on common/src/main/java/org/dash/wallet/common/ui/FancyAlertDialog.kt
> +    var onFancyAlertButtonsClickListener: FancyAlertButtonsClickListener? = null
I agree with removing `FancyAlertDialogViewModel` and use lamda's instead for the click listeners as a separate action.

2022-01-18 10:05 UTC, ClaudeHangui commented
there were some work from Hadia that I forgot to update accordingly, working on the fixes

2022-01-18 13:48 UTC, Syn-McJ approved these changes
Looks good

2022-01-19 03:43 UTC, Syn-McJ approved these changes
Looks great

2022-01-19 05:04 UTC, merged