feat: forcefully log out coinbase user when token is expired or invalid
dashevo/dash-wallet pull request #907
Opened 2022-03-01 17:11 UTC by ClaudeHangui

## Issue being fixed or feature implemented
When the user's token is invalid/revoked for whatever reason, we should forcefully log out the user from Coinbase so that he can login again and get a new token

## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ x] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2022-03-01 17:22 UTC, ClaudeHangui commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt
> +    val entryPoint = EntryPointAccessors.fromApplication(context, CoinbasePortalEntryPoint::class.java)
We needed to inject our broadcast class in a non android class. This call allows us to to that.
We needed an instance of the Context class, thus, it had to be provided as a dependency

2022-03-01 19:05 UTC, HashEngineering approved these changes

2022-03-02 08:26 UTC, Syn-McJ commented on integrations/coinbase-integration/src/main/java/org/dash/wallet/integration/coinbase_integration/repository/remote/TokenAuthenticator.kt
> +    val entryPoint = EntryPointAccessors.fromApplication(context, CoinbasePortalEntryPoint::class.java)
Generally, when you find yourself needing to inject something into a class that isn't an Android component and doesn't support injection, it pays to stop and think if this is the right place to do the injection.

`TokenAuthenticator` seems like a fairly generic class that could be reused across features with some modifications, but now not only it is tied specifically to Coinbase, but also it is aware of the context, our dependency framework, and responsible for broadcasting changes. Quite a lot of SOLID principles are broken here.

2022-03-02 08:46 UTC, Syn-McJ requested changes
@ClaudeHangui I have an issue with this solution for broadcasting authentication state from the `TokenAuthenticator`. First, this type of broadcasting is a lazy pattern that makes it difficult to follow the logical flow and allows listening to the broadcast from anywhere in the app which isn't a good thing. Second, it complicates the chain of dependencies. A good chain of dependencies looks like this: 
<img src="https://user-images.githubusercontent.com/7733989/156325271-3d7082a3-ec68-4d22-852a-5daec931bf1a.jpg" width="300" />
While a bad one looks like this:

<img src="https://user-images.githubusercontent.com/7733989/156325345-dd8e1f9e-5866-4afb-afbd-3f99ea653a59.jpg" width="300" />

Additionally, `CoinbaseActivity` already has a ViewModel that can be used for this type of communication. Perhaps we can use the exception throwing mechanism, catching it down the line closer to the viewModel and listening to the event through the viewModel.

There is also a `CoinBaseAuthRepository` class that doesn't seem to be used but could be more suitable for handling this error.

Could you please investigate if an alternative solution of this kind can be used?

2022-03-02 10:31 UTC, closed without merging