feat: transfer dash to/from coinbase
dashevo/dash-wallet pull request #940
Opened 2022-04-26 13:44 UTC by ClaudeHangui

As a user we want to be able to transfer Dash to/from Coinbase from/to the Dash Wallet
## Issue being fixed or feature implemented

- A custom view (i.e `ConvertView`) to handle swap direction change has already been provided (by Hadia) from `Convert Crypto` story/code; however it appears there has been some change in the design for this view. This design change has been submitted after the story has been done. As far as the `Transfer Dash` story is concerned, it has to be provided with the new design. I assume the design changes related to Crypto Conversion will be done in another story.
So in other to prevent any future conflict with the custom `ConvertView` class, we decided to create our custom view but using the same xml file

- Completing the transfer from Dash -> Coinbase requires authentication either by PIN, FaceID: the classes used to construct and therefore handle PIN/FaceID authentications are in the `wallet` module. So, in other to properly use those components, we hade to move the corresponding VM's (`SingleActionSharedViewModel` && `CheckPinSharedModel`) used in the authentication from `wallet -> common` to handle authentication states and define an interactor/interface to display the PIN/FaceId dialogs

## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ ] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2022-04-26 15:21 UTC, Syn-McJ requested changes
You had the right idea about `PinInteractor`, however, the dialog itself can be extended to use callback or coroutine for returning the result. This way, there is no need to move `CheckPinSharedModel` around and we can get rid of it later.

I have already done this for CrowdNode, let me create a quick PR to maser which you can then integrate.

2022-04-27 05:33 UTC, HashEngineering commented
@ClaudeHangui The PR #941  has been merged to master.

2022-04-29 17:03 UTC, ClaudeHangui commented
@Syn-McJ I made the changes as per your suggestions; please check this out

2022-04-30 07:08 UTC, Syn-McJ requested changes
@ClaudeHangui changes with pin dialog look good, however I have a small change request for the `ConfirmTransactionDialog`, see the comments.

2022-04-30 07:08 UTC, Syn-McJ commented on wallet/src/de/schildbach/wallet/ui/UpholdTransferActivity.kt
> +                ConfirmTransactionDialog.createDialog(this@UpholdTransferActivity, address, amountStr, amountFiat, fiatSymbol, fee, total, getString(R.string.uphold_transfer))
@ClaudeHangui isn't a call to `dialog.show()` needed here?

2022-04-30 07:08 UTC, Syn-McJ commented on wallet/src/de/schildbach/wallet/ui/send/ConfirmTransactionDialog.kt
> +            showDialog(dialog, bundle, activity)
@ClaudeHangui it's not obvious that `createDialog` calls `show`. These should either be different methods like in `AdaptiveDialog`, or this method should be renamed

2022-04-30 08:32 UTC, Syn-McJ approved these changes
Looks great

2022-05-01 05:44 UTC, HashEngineering approved these changes

2022-05-01 05:45 UTC, merged